### ISSUE TITLE
About high-LD-regions.txt

### ISSUE THREAD

**Issue by mxqian** [wuttke/gwas#1]
Hi Wuttke,

Do you know which genome version for this file?  I guess it should hg18, but I cannot find the declaration anywhere, even in the original paper.  And I try to liftOver to hg19, but conversion failed on 7 records.
Do you have any suggestion?  Many thanks in advance.

Max

**Comment by wuttke** [comment]
Hi, the file is hg18, but there is also a hg19 version.
See here: https://github.com/wuttke/gwas/blob/master/cleaning-pipeline/aux/high-LD-regions_hg19.txt

**Comment by test12138jooh** [comment]
Hi Wuttke,

Why the high-LD-regions_hg19.txt only included 18 regions? It seems that the first publication about this contain 24 regions?

Best,
Jun

**Comment by wuttke** [comment]
Might be related to liftOver?I do not recall specific differences MatthiasAm 06.05.2024 um 04:36 schrieb test12138jooh ***@***.***>:﻿
Hi Wuttke,
Why the high-LD-regions_hg19.txt only included 18 regions? It seems that the first publication about this contain 24 regions?
Best,
Jun
